//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCrud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int Sales { get; set; }
        public int Shrink { get; set; }
        public int UserID { get; set; }
    
        public virtual PrimaryUser PrimaryUser { get; set; }
    }
}
